# Generated by Django 4.1.3 on 2022-11-02 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_delete_author_remove_article_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
