# Generated by Django 4.1.3 on 2022-11-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_article_author_article_description_article_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='urlToImage',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
