# Generated by Django 4.1.3 on 2022-11-02 15:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_article_author_alter_article_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publishedAt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 2, 15, 8, 14, 277934, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
