# Generated by Django 4.1.3 on 2022-11-02 15:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_alter_article_publishedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publishedAt',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
